### ISSUE TITLE
How to generate a .heic file with brand heix？

### ISSUE THREAD

**Issue by wuKylin** [nokiatech/heif#71]
As the technical information shows, the heif format support 10-bit. However , i met a error when i try to generate a heic file with brand heix. My codes are as follows:
```
       HEIF heif = new HEIF();
	try
	{
		// generate encode data
		// the coding format is HEVC( **Main 10** )

		// generate a imageItem according to the encode data
		HEVCImageItem imageItem = new HEVCImageItem(heif, new Size(width, height),
				decoderConfig, imageData);
		heif.setPrimaryImage(imageItem);

		// The brands need to be set
		heif.setMajorBrand(HEIF.BRAND_MIF1);
		heif.addCompatibleBrand(HEIF.BRAND_HEIX);

		// And we save the file
		heif.save("/sdcard/1.heic");
	}
	// All exceptions thrown by the HEIF library are of the same type
	// Check the error code to see what happened
	catch (Exception e)
	{
		e.printStackTrace();
	}
```

The error is as follows, are there other api need to be set?
```
W/System.err: com.nokia.heif.Exception: Saving failed UNDEFINED_ERROR
W/System.err:     at com.nokia.heif.ErrorHandler.throwException(ErrorHandler.java:97)
W/System.err:     at com.nokia.heif.HEIF.saveNative(Native Method)
W/System.err:     at com.nokia.heif.HEIF.save(HEIF.java:229)
```

**Comment by kingvhit** [comment]
Did you find any solution for this request? I still have the same problems.
